name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.18' # Change this to the version you need

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Adjust the build command based on your project

    - name: Run tests
      run: npm test  # Adjust the test command based on your project
